// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_DataBundles_screen_init(void)
{
  ui_DataBundles = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_DataBundles, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundles, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Widget3 = lv_obj_create(ui_DataBundles);
  lv_obj_remove_style_all(ui_Widget3);
  lv_obj_set_width(ui_Widget3, 760);
  lv_obj_set_height(ui_Widget3, 440);
  lv_obj_set_align(ui_Widget3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Widget3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
           LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
           LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);   /// Flags
  lv_obj_set_style_radius(ui_Widget3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Widget3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Widget3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_Widget3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_Widget3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_Widget3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundlePageWatcher = lv_obj_create(ui_Widget3);
  lv_obj_remove_style_all(ui_DataBundlePageWatcher);
  lv_obj_set_width(ui_DataBundlePageWatcher, 80);
  lv_obj_set_height(ui_DataBundlePageWatcher, 15);
  lv_obj_set_x(ui_DataBundlePageWatcher, 0);
  lv_obj_set_y(ui_DataBundlePageWatcher, -35);
  lv_obj_set_align(ui_DataBundlePageWatcher, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundlePageWatcher, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_DataBundlePageWatcherCell = lv_obj_create(ui_DataBundlePageWatcher);
  lv_obj_remove_style_all(ui_DataBundlePageWatcherCell);
  lv_obj_set_width(ui_DataBundlePageWatcherCell, 12);
  lv_obj_set_height(ui_DataBundlePageWatcherCell, 12);
  lv_obj_set_x(ui_DataBundlePageWatcherCell, -30);
  lv_obj_set_y(ui_DataBundlePageWatcherCell, 0);
  lv_obj_set_align(ui_DataBundlePageWatcherCell, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundlePageWatcherCell, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundlePageWatcherCell, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundlePageWatcherCell, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundlePageWatcherCell, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_DataBundlePageWatcherCell, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_DataBundlePageWatcherCell, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_DataBundlePageWatcherCell, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundlePageWatcherCell1 = lv_obj_create(ui_DataBundlePageWatcher);
  lv_obj_remove_style_all(ui_DataBundlePageWatcherCell1);
  lv_obj_set_width(ui_DataBundlePageWatcherCell1, 12);
  lv_obj_set_height(ui_DataBundlePageWatcherCell1, 12);
  lv_obj_set_x(ui_DataBundlePageWatcherCell1, -15);
  lv_obj_set_y(ui_DataBundlePageWatcherCell1, 0);
  lv_obj_set_align(ui_DataBundlePageWatcherCell1, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundlePageWatcherCell1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundlePageWatcherCell1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundlePageWatcherCell1, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundlePageWatcherCell1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_DataBundlePageWatcherCell1, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_DataBundlePageWatcherCell1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_DataBundlePageWatcherCell1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundlePageWatcherCell2 = lv_obj_create(ui_DataBundlePageWatcher);
  lv_obj_remove_style_all(ui_DataBundlePageWatcherCell2);
  lv_obj_set_width(ui_DataBundlePageWatcherCell2, 12);
  lv_obj_set_height(ui_DataBundlePageWatcherCell2, 12);
  lv_obj_set_align(ui_DataBundlePageWatcherCell2, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundlePageWatcherCell2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundlePageWatcherCell2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundlePageWatcherCell2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundlePageWatcherCell2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_DataBundlePageWatcherCell2, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_DataBundlePageWatcherCell2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_DataBundlePageWatcherCell2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundlePageWatcherCell3 = lv_obj_create(ui_DataBundlePageWatcher);
  lv_obj_remove_style_all(ui_DataBundlePageWatcherCell3);
  lv_obj_set_width(ui_DataBundlePageWatcherCell3, 12);
  lv_obj_set_height(ui_DataBundlePageWatcherCell3, 12);
  lv_obj_set_x(ui_DataBundlePageWatcherCell3, 15);
  lv_obj_set_y(ui_DataBundlePageWatcherCell3, 0);
  lv_obj_set_align(ui_DataBundlePageWatcherCell3, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundlePageWatcherCell3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundlePageWatcherCell3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundlePageWatcherCell3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundlePageWatcherCell3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_DataBundlePageWatcherCell3, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_DataBundlePageWatcherCell3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_DataBundlePageWatcherCell3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundlePageWatcherCell4 = lv_obj_create(ui_DataBundlePageWatcher);
  lv_obj_remove_style_all(ui_DataBundlePageWatcherCell4);
  lv_obj_set_width(ui_DataBundlePageWatcherCell4, 12);
  lv_obj_set_height(ui_DataBundlePageWatcherCell4, 12);
  lv_obj_set_x(ui_DataBundlePageWatcherCell4, 30);
  lv_obj_set_y(ui_DataBundlePageWatcherCell4, 0);
  lv_obj_set_align(ui_DataBundlePageWatcherCell4, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundlePageWatcherCell4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundlePageWatcherCell4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundlePageWatcherCell4, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundlePageWatcherCell4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_DataBundlePageWatcherCell4, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_DataBundlePageWatcherCell4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_DataBundlePageWatcherCell4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundle = lv_obj_create(ui_Widget3);
  lv_obj_remove_style_all(ui_DataBundle);
  lv_obj_set_width(ui_DataBundle, 200);
  lv_obj_set_height(ui_DataBundle, 160);
  lv_obj_set_x(ui_DataBundle, -250);
  lv_obj_set_y(ui_DataBundle, -70);
  lv_obj_set_align(ui_DataBundle, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_DataBundle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
           LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
           LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);   /// Flags

  ui_DataBundleHeaderGroup = lv_obj_create(ui_DataBundle);
  lv_obj_remove_style_all(ui_DataBundleHeaderGroup);
  lv_obj_set_width(ui_DataBundleHeaderGroup, 200);
  lv_obj_set_height(ui_DataBundleHeaderGroup, 20);
  lv_obj_set_align(ui_DataBundleHeaderGroup, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_DataBundleHeaderGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_DataBundleHeaderCornerBottomLeft = lv_obj_create(ui_DataBundleHeaderGroup);
  lv_obj_remove_style_all(ui_DataBundleHeaderCornerBottomLeft);
  lv_obj_set_width(ui_DataBundleHeaderCornerBottomLeft, 10);
  lv_obj_set_height(ui_DataBundleHeaderCornerBottomLeft, 10);
  lv_obj_set_align(ui_DataBundleHeaderCornerBottomLeft, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_DataBundleHeaderCornerBottomLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleHeaderCornerBottomLeft, lv_color_hex(0x007CCC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleHeaderCornerBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_DataBundleHeaderCornerBottomLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleHeaderCornerBottomRight = lv_obj_create(ui_DataBundleHeaderGroup);
  lv_obj_remove_style_all(ui_DataBundleHeaderCornerBottomRight);
  lv_obj_set_width(ui_DataBundleHeaderCornerBottomRight, 10);
  lv_obj_set_height(ui_DataBundleHeaderCornerBottomRight, 10);
  lv_obj_set_align(ui_DataBundleHeaderCornerBottomRight, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_clear_flag(ui_DataBundleHeaderCornerBottomRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleHeaderCornerBottomRight, lv_color_hex(0x007CCC),
               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleHeaderCornerBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_DataBundleHeaderCornerBottomRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleHeader = lv_obj_create(ui_DataBundleHeaderGroup);
  lv_obj_remove_style_all(ui_DataBundleHeader);
  lv_obj_set_width(ui_DataBundleHeader, 200);
  lv_obj_set_height(ui_DataBundleHeader, 20);
  lv_obj_set_align(ui_DataBundleHeader, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_DataBundleHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundleHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundleHeader, lv_color_hex(0x007CCC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleHeaderLabel = lv_label_create(ui_DataBundleHeader);
  lv_obj_set_width(ui_DataBundleHeaderLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_DataBundleHeaderLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_DataBundleHeaderLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_DataBundleHeaderLabel, "DHT11 temperature");
  lv_obj_set_style_text_font(ui_DataBundleHeaderLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleChart = lv_chart_create(ui_DataBundle);
  lv_obj_set_width(ui_DataBundleChart, 200);
  lv_obj_set_height(ui_DataBundleChart, 110);
  lv_obj_set_x(ui_DataBundleChart, 0);
  lv_obj_set_y(ui_DataBundleChart, -4);
  lv_obj_set_align(ui_DataBundleChart, LV_ALIGN_CENTER);
  lv_chart_set_type(ui_DataBundleChart, LV_CHART_TYPE_LINE);
  lv_chart_set_div_line_count(ui_DataBundleChart, 5, 10);
  lv_chart_set_axis_tick(ui_DataBundleChart, LV_CHART_AXIS_PRIMARY_X, 9, 0, 10, 1, false, 50);
  lv_chart_set_axis_tick(ui_DataBundleChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
  lv_chart_set_axis_tick(ui_DataBundleChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
  lv_chart_series_t * ui_DataBundleChart_series_1 = lv_chart_add_series(ui_DataBundleChart, lv_color_hex(0xFF8200),
                                     LV_CHART_AXIS_PRIMARY_Y);
  static lv_coord_t ui_DataBundleChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
  lv_chart_set_ext_y_array(ui_DataBundleChart, ui_DataBundleChart_series_1, ui_DataBundleChart_series_1_array);
  lv_obj_set_style_radius(ui_DataBundleChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundleChart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterGroup = lv_obj_create(ui_DataBundle);
  lv_obj_remove_style_all(ui_DataBundleFooterGroup);
  lv_obj_set_width(ui_DataBundleFooterGroup, 200);
  lv_obj_set_height(ui_DataBundleFooterGroup, 30);
  lv_obj_set_align(ui_DataBundleFooterGroup, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_DataBundleFooterGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_DataBundleFooterBridge = lv_obj_create(ui_DataBundleFooterGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterBridge);
  lv_obj_set_width(ui_DataBundleFooterBridge, 40);
  lv_obj_set_height(ui_DataBundleFooterBridge, 15);
  lv_obj_set_x(ui_DataBundleFooterBridge, 25);
  lv_obj_set_y(ui_DataBundleFooterBridge, -7);
  lv_obj_set_align(ui_DataBundleFooterBridge, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_DataBundleFooterBridge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleFooterBridge, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterBridge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterBridgeFill = lv_obj_create(ui_DataBundleFooterGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterBridgeFill);
  lv_obj_set_width(ui_DataBundleFooterBridgeFill, 25);
  lv_obj_set_height(ui_DataBundleFooterBridgeFill, 15);
  lv_obj_set_x(ui_DataBundleFooterBridgeFill, 17);
  lv_obj_set_y(ui_DataBundleFooterBridgeFill, -1);
  lv_obj_set_align(ui_DataBundleFooterBridgeFill, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_DataBundleFooterBridgeFill, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundleFooterBridgeFill, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundleFooterBridgeFill, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterBridgeFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterTimerGroup = lv_obj_create(ui_DataBundleFooterGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterTimerGroup);
  lv_obj_set_width(ui_DataBundleFooterTimerGroup, 105);
  lv_obj_set_height(ui_DataBundleFooterTimerGroup, 20);
  lv_obj_set_x(ui_DataBundleFooterTimerGroup, 0);
  lv_obj_set_y(ui_DataBundleFooterTimerGroup, -9);
  lv_obj_set_align(ui_DataBundleFooterTimerGroup, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_DataBundleFooterTimerGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_DataBundleFooterDateCornerTopLeft = lv_obj_create(ui_DataBundleFooterTimerGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterDateCornerTopLeft);
  lv_obj_set_width(ui_DataBundleFooterDateCornerTopLeft, 10);
  lv_obj_set_height(ui_DataBundleFooterDateCornerTopLeft, 10);
  lv_obj_clear_flag(ui_DataBundleFooterDateCornerTopLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleFooterDateCornerTopLeft, lv_color_hex(0x055DA9),
               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterDateCornerTopLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_DataBundleFooterDateCornerTopLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterDateCornerTopRight = lv_obj_create(ui_DataBundleFooterTimerGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterDateCornerTopRight);
  lv_obj_set_width(ui_DataBundleFooterDateCornerTopRight, 10);
  lv_obj_set_height(ui_DataBundleFooterDateCornerTopRight, 10);
  lv_obj_set_align(ui_DataBundleFooterDateCornerTopRight, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_DataBundleFooterDateCornerTopRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleFooterDateCornerTopRight, lv_color_hex(0x055DA9),
               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterDateCornerTopRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_DataBundleFooterDateCornerTopRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterDate = lv_obj_create(ui_DataBundleFooterTimerGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterDate);
  lv_obj_set_width(ui_DataBundleFooterDate, 105);
  lv_obj_set_height(ui_DataBundleFooterDate, 20);
  lv_obj_set_align(ui_DataBundleFooterDate, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_DataBundleFooterDate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundleFooterDate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundleFooterDate, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterLabelDate = lv_label_create(ui_DataBundleFooterDate);
  lv_obj_set_width(ui_DataBundleFooterLabelDate, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_DataBundleFooterLabelDate, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_DataBundleFooterLabelDate, 7);
  lv_obj_set_y(ui_DataBundleFooterLabelDate, 0);
  lv_obj_set_align(ui_DataBundleFooterLabelDate, LV_ALIGN_LEFT_MID);
  lv_label_set_text(ui_DataBundleFooterLabelDate, "21.12.2026");
  lv_obj_set_style_text_font(ui_DataBundleFooterLabelDate, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterLabelTime = lv_label_create(ui_DataBundleFooterDate);
  lv_obj_set_width(ui_DataBundleFooterLabelTime, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_DataBundleFooterLabelTime, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_DataBundleFooterLabelTime, -5);
  lv_obj_set_y(ui_DataBundleFooterLabelTime, 0);
  lv_obj_set_align(ui_DataBundleFooterLabelTime, LV_ALIGN_RIGHT_MID);
  lv_label_set_text(ui_DataBundleFooterLabelTime, "16:00");
  lv_obj_set_style_text_font(ui_DataBundleFooterLabelTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterButtonsGroup = lv_obj_create(ui_DataBundleFooterGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterButtonsGroup);
  lv_obj_set_width(ui_DataBundleFooterButtonsGroup, 70);
  lv_obj_set_height(ui_DataBundleFooterButtonsGroup, 30);
  lv_obj_set_x(ui_DataBundleFooterButtonsGroup, 0);
  lv_obj_set_y(ui_DataBundleFooterButtonsGroup, 1);
  lv_obj_set_align(ui_DataBundleFooterButtonsGroup, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_clear_flag(ui_DataBundleFooterButtonsGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_DataBundleFooterButtonsCornerTopLeft = lv_obj_create(ui_DataBundleFooterButtonsGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterButtonsCornerTopLeft);
  lv_obj_set_width(ui_DataBundleFooterButtonsCornerTopLeft, 10);
  lv_obj_set_height(ui_DataBundleFooterButtonsCornerTopLeft, 10);
  lv_obj_clear_flag(ui_DataBundleFooterButtonsCornerTopLeft,
           LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleFooterButtonsCornerTopLeft, lv_color_hex(0x055DA9),
               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterButtonsCornerTopLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_DataBundleFooterButtonsCornerTopLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterButtonsCornerTopRight = lv_obj_create(ui_DataBundleFooterButtonsGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterButtonsCornerTopRight);
  lv_obj_set_width(ui_DataBundleFooterButtonsCornerTopRight, 10);
  lv_obj_set_height(ui_DataBundleFooterButtonsCornerTopRight, 10);
  lv_obj_set_align(ui_DataBundleFooterButtonsCornerTopRight, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_DataBundleFooterButtonsCornerTopRight,
           LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_DataBundleFooterButtonsCornerTopRight, lv_color_hex(0x055DA9),
               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterButtonsCornerTopRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_DataBundleFooterButtonsCornerTopRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterButtons = lv_obj_create(ui_DataBundleFooterButtonsGroup);
  lv_obj_remove_style_all(ui_DataBundleFooterButtons);
  lv_obj_set_width(ui_DataBundleFooterButtons, 70);
  lv_obj_set_height(ui_DataBundleFooterButtons, 30);
  lv_obj_set_align(ui_DataBundleFooterButtons, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_DataBundleFooterButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundleFooterButtons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DataBundleFooterButtons, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DataBundleFooterButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterButtonExport = lv_btn_create(ui_DataBundleFooterButtons);
  lv_obj_set_width(ui_DataBundleFooterButtonExport, 28);
  lv_obj_set_height(ui_DataBundleFooterButtonExport, 24);
  lv_obj_set_x(ui_DataBundleFooterButtonExport, 5);
  lv_obj_set_y(ui_DataBundleFooterButtonExport, -1);
  lv_obj_set_align(ui_DataBundleFooterButtonExport, LV_ALIGN_LEFT_MID);
  lv_obj_add_flag(ui_DataBundleFooterButtonExport, LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
  lv_obj_clear_flag(ui_DataBundleFooterButtonExport, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundleFooterButtonExport, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterButtonExportImage = lv_img_create(ui_DataBundleFooterButtonExport);
  lv_img_set_src(ui_DataBundleFooterButtonExportImage, &ui_img_export_png);
  lv_obj_set_width(ui_DataBundleFooterButtonExportImage, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_DataBundleFooterButtonExportImage, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_DataBundleFooterButtonExportImage, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_DataBundleFooterButtonExportImage, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_DataBundleFooterButtonExportImage, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_img_set_zoom(ui_DataBundleFooterButtonExportImage, 81);

  ui_DataBundleFooterButtonClear = lv_btn_create(ui_DataBundleFooterButtons);
  lv_obj_set_width(ui_DataBundleFooterButtonClear, 28);
  lv_obj_set_height(ui_DataBundleFooterButtonClear, 24);
  lv_obj_set_x(ui_DataBundleFooterButtonClear, -5);
  lv_obj_set_y(ui_DataBundleFooterButtonClear, -1);
  lv_obj_set_align(ui_DataBundleFooterButtonClear, LV_ALIGN_RIGHT_MID);
  lv_obj_add_flag(ui_DataBundleFooterButtonClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
  lv_obj_clear_flag(ui_DataBundleFooterButtonClear, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_DataBundleFooterButtonClear, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DataBundleFooterButtonClearImage = lv_img_create(ui_DataBundleFooterButtonClear);
  lv_img_set_src(ui_DataBundleFooterButtonClearImage, &ui_img_trashicon_png);
  lv_obj_set_width(ui_DataBundleFooterButtonClearImage, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_DataBundleFooterButtonClearImage, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_DataBundleFooterButtonClearImage, -1);
  lv_obj_set_y(ui_DataBundleFooterButtonClearImage, 0);
  lv_obj_set_align(ui_DataBundleFooterButtonClearImage, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_DataBundleFooterButtonClearImage, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_DataBundleFooterButtonClearImage, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_img_set_zoom(ui_DataBundleFooterButtonClearImage, 81);

  /*ui_LogoGroup3 = lv_obj_create(ui_Widget3);
  lv_obj_remove_style_all(ui_LogoGroup3);
  lv_obj_set_width(ui_LogoGroup3, 100);
  lv_obj_set_height(ui_LogoGroup3, 25);
  lv_obj_set_align(ui_LogoGroup3, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_LogoGroup3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_LogoCornerBottomLeft3 = lv_obj_create(ui_LogoGroup3);
  lv_obj_remove_style_all(ui_LogoCornerBottomLeft3);
  lv_obj_set_width(ui_LogoCornerBottomLeft3, 20);
  lv_obj_set_height(ui_LogoCornerBottomLeft3, 10);
  lv_obj_set_align(ui_LogoCornerBottomLeft3, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_LogoCornerBottomLeft3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_LogoCornerBottomLeft3, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_LogoCornerBottomLeft3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_LogoCornerBottomLeft3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_LogoCornerFillBottomLeft3 = lv_obj_create(ui_LogoGroup3);
  lv_obj_remove_style_all(ui_LogoCornerFillBottomLeft3);
  lv_obj_set_width(ui_LogoCornerFillBottomLeft3, 15);
  lv_obj_set_height(ui_LogoCornerFillBottomLeft3, 15);
  lv_obj_set_x(ui_LogoCornerFillBottomLeft3, -5);
  lv_obj_set_y(ui_LogoCornerFillBottomLeft3, 0);
  lv_obj_set_align(ui_LogoCornerFillBottomLeft3, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_LogoCornerFillBottomLeft3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_LogoCornerFillBottomLeft3, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_LogoCornerFillBottomLeft3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomLeft3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomLeft3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_LogoCornerBottomRight3 = lv_obj_create(ui_LogoGroup3);
  lv_obj_remove_style_all(ui_LogoCornerBottomRight3);
  lv_obj_set_width(ui_LogoCornerBottomRight3, 20);
  lv_obj_set_height(ui_LogoCornerBottomRight3, 10);
  lv_obj_set_align(ui_LogoCornerBottomRight3, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_clear_flag(ui_LogoCornerBottomRight3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_LogoCornerBottomRight3, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_LogoCornerBottomRight3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_LogoCornerBottomRight3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_LogoCornerFillBottomRight3 = lv_obj_create(ui_LogoGroup3);
  lv_obj_remove_style_all(ui_LogoCornerFillBottomRight3);
  lv_obj_set_width(ui_LogoCornerFillBottomRight3, 15);
  lv_obj_set_height(ui_LogoCornerFillBottomRight3, 15);
  lv_obj_set_x(ui_LogoCornerFillBottomRight3, 5);
  lv_obj_set_y(ui_LogoCornerFillBottomRight3, 0);
  lv_obj_set_align(ui_LogoCornerFillBottomRight3, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_clear_flag(ui_LogoCornerFillBottomRight3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_LogoCornerFillBottomRight3, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_LogoCornerFillBottomRight3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomRight3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomRight3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_LogoOutlay3 = lv_obj_create(ui_LogoGroup3);
  lv_obj_remove_style_all(ui_LogoOutlay3);
  lv_obj_set_width(ui_LogoOutlay3, 80);
  lv_obj_set_height(ui_LogoOutlay3, 25);
  lv_obj_set_align(ui_LogoOutlay3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_LogoOutlay3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_LogoOutlay3, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_LogoOutlay3, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_LogoOutlay3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_LogoOutlay3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_LogoImage3 = lv_img_create(ui_LogoGroup3);
  lv_img_set_src(ui_LogoImage3, &ui_img_mtalogo_png);
  lv_obj_set_width(ui_LogoImage3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_LogoImage3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_LogoImage3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_LogoImage3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
           LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_img_set_zoom(ui_LogoImage3, 80);*/

  ui_DataBundlesLabel = lv_label_create(ui_Widget3);
  lv_obj_set_width(ui_DataBundlesLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_DataBundlesLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_DataBundlesLabel, 0);
  lv_obj_set_y(ui_DataBundlesLabel, 10);
  lv_obj_set_align(ui_DataBundlesLabel, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_DataBundlesLabel, "Data Bundles");
  lv_obj_clear_flag(ui_DataBundlesLabel,
           LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
           LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
           LV_OBJ_FLAG_SCROLL_CHAIN);   /// Flags
  lv_obj_set_style_text_color(ui_DataBundlesLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_DataBundlesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_DataBundlesLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBackGroup1 = lv_obj_create(ui_Widget3);
  lv_obj_remove_style_all(ui_ButtonBackGroup1);
  lv_obj_set_width(ui_ButtonBackGroup1, 100);
  lv_obj_set_height(ui_ButtonBackGroup1, 40);
  lv_obj_clear_flag(ui_ButtonBackGroup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_ButtonBackCornerBottomLeft1 = lv_obj_create(ui_ButtonBackGroup1);
  lv_obj_remove_style_all(ui_ButtonBackCornerBottomLeft1);
  lv_obj_set_width(ui_ButtonBackCornerBottomLeft1, 20);
  lv_obj_set_height(ui_ButtonBackCornerBottomLeft1, 20);
  lv_obj_set_align(ui_ButtonBackCornerBottomLeft1, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_ButtonBackCornerBottomLeft1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_ButtonBackCornerBottomLeft1, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonBackCornerBottomLeft1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_ButtonBackCornerBottomLeft1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBackCornerTopRight1 = lv_obj_create(ui_ButtonBackGroup1);
  lv_obj_remove_style_all(ui_ButtonBackCornerTopRight1);
  lv_obj_set_width(ui_ButtonBackCornerTopRight1, 20);
  lv_obj_set_height(ui_ButtonBackCornerTopRight1, 20);
  lv_obj_set_align(ui_ButtonBackCornerTopRight1, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_ButtonBackCornerTopRight1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_ButtonBackCornerTopRight1, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonBackCornerTopRight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_ButtonBackCornerTopRight1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_btnBack1 = lv_btn_create(ui_ButtonBackGroup1);
  lv_obj_set_width(ui_btnBack1, 100);
  lv_obj_set_height(ui_btnBack1, 40);
  lv_obj_add_flag(ui_btnBack1, LV_OBJ_FLAG_EVENT_BUBBLE);   /// Flags
  lv_obj_clear_flag(ui_btnBack1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
           LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
           LV_OBJ_FLAG_SCROLL_CHAIN);   /// Flags
  lv_obj_set_style_clip_corner(ui_btnBack1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBackLabel1 = lv_label_create(ui_btnBack1);
  lv_obj_set_width(ui_ButtonBackLabel1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_ButtonBackLabel1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_ButtonBackLabel1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ButtonBackLabel1, "Back");
  lv_obj_set_style_text_font(ui_ButtonBackLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonNextGroup = lv_obj_create(ui_Widget3);
  lv_obj_remove_style_all(ui_ButtonNextGroup);
  lv_obj_set_width(ui_ButtonNextGroup, 100);
  lv_obj_set_height(ui_ButtonNextGroup, 40);
  lv_obj_set_x(ui_ButtonNextGroup, 160);
  lv_obj_set_y(ui_ButtonNextGroup, 0);
  lv_obj_set_align(ui_ButtonNextGroup, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_ButtonNextGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_ButtonNextCornerBottomLeft = lv_obj_create(ui_ButtonNextGroup);
  lv_obj_remove_style_all(ui_ButtonNextCornerBottomLeft);
  lv_obj_set_width(ui_ButtonNextCornerBottomLeft, 20);
  lv_obj_set_height(ui_ButtonNextCornerBottomLeft, 20);
  lv_obj_set_align(ui_ButtonNextCornerBottomLeft, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_ButtonNextCornerBottomLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_ButtonNextCornerBottomLeft, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonNextCornerBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_ButtonNextCornerBottomLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonNextCornerBottomRight = lv_obj_create(ui_ButtonNextGroup);
  lv_obj_remove_style_all(ui_ButtonNextCornerBottomRight);
  lv_obj_set_width(ui_ButtonNextCornerBottomRight, 20);
  lv_obj_set_height(ui_ButtonNextCornerBottomRight, 20);
  lv_obj_set_align(ui_ButtonNextCornerBottomRight, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_clear_flag(ui_ButtonNextCornerBottomRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_ButtonNextCornerBottomRight, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonNextCornerBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_ButtonNextCornerBottomRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_btnNext = lv_btn_create(ui_ButtonNextGroup);
  lv_obj_set_width(ui_btnNext, 100);
  lv_obj_set_height(ui_btnNext, 40);
  lv_obj_set_align(ui_btnNext, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_btnNext, LV_OBJ_FLAG_EVENT_BUBBLE);   /// Flags
  lv_obj_clear_flag(ui_btnNext, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
           LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
           LV_OBJ_FLAG_SCROLL_CHAIN);   /// Flags

  ui_ButtonNextLabel = lv_label_create(ui_btnNext);
  lv_obj_set_width(ui_ButtonNextLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_ButtonNextLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_ButtonNextLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ButtonNextLabel, "Next");

  ui_ButtonPrevGroup = lv_obj_create(ui_Widget3);
  lv_obj_remove_style_all(ui_ButtonPrevGroup);
  lv_obj_set_width(ui_ButtonPrevGroup, 100);
  lv_obj_set_height(ui_ButtonPrevGroup, 40);
  lv_obj_set_x(ui_ButtonPrevGroup, -160);
  lv_obj_set_y(ui_ButtonPrevGroup, 0);
  lv_obj_set_align(ui_ButtonPrevGroup, LV_ALIGN_BOTTOM_MID);
  lv_obj_clear_flag(ui_ButtonPrevGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags

  ui_ButtonPrevCornerBottomLeft = lv_obj_create(ui_ButtonPrevGroup);
  lv_obj_remove_style_all(ui_ButtonPrevCornerBottomLeft);
  lv_obj_set_width(ui_ButtonPrevCornerBottomLeft, 20);
  lv_obj_set_height(ui_ButtonPrevCornerBottomLeft, 20);
  lv_obj_set_align(ui_ButtonPrevCornerBottomLeft, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_ButtonPrevCornerBottomLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_ButtonPrevCornerBottomLeft, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonPrevCornerBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_ButtonPrevCornerBottomLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonPrevCornerBottomRight = lv_obj_create(ui_ButtonPrevGroup);
  lv_obj_remove_style_all(ui_ButtonPrevCornerBottomRight);
  lv_obj_set_width(ui_ButtonPrevCornerBottomRight, 20);
  lv_obj_set_height(ui_ButtonPrevCornerBottomRight, 20);
  lv_obj_set_align(ui_ButtonPrevCornerBottomRight, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_clear_flag(ui_ButtonPrevCornerBottomRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_bg_color(ui_ButtonPrevCornerBottomRight, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonPrevCornerBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_clip_corner(ui_ButtonPrevCornerBottomRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_btnPrev = lv_btn_create(ui_ButtonPrevGroup);
  lv_obj_set_width(ui_btnPrev, 100);
  lv_obj_set_height(ui_btnPrev, 40);
  lv_obj_set_align(ui_btnPrev, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_btnPrev, LV_OBJ_FLAG_EVENT_BUBBLE);   /// Flags
  lv_obj_clear_flag(ui_btnPrev, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
           LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
           LV_OBJ_FLAG_SCROLL_CHAIN);   /// Flags

  ui_ButtonPrevLabel3 = lv_label_create(ui_btnPrev);
  lv_obj_set_width(ui_ButtonPrevLabel3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_ButtonPrevLabel3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_ButtonPrevLabel3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ButtonPrevLabel3, "Prev");

}