// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Widget2 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Widget2);
    lv_obj_set_width(ui_Widget2, 760);
    lv_obj_set_height(ui_Widget2, 440);
    lv_obj_set_align(ui_Widget2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Widget2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Widget2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Widget2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Widget2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Widget2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Widget2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Widget2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoGroup2 = lv_obj_create(ui_Widget2);
    lv_obj_remove_style_all(ui_LogoGroup2);
    lv_obj_set_width(ui_LogoGroup2, 100);
    lv_obj_set_height(ui_LogoGroup2, 25);
    lv_obj_set_align(ui_LogoGroup2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_LogoGroup2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoCornerBottomLeft2 = lv_obj_create(ui_LogoGroup2);
    lv_obj_remove_style_all(ui_LogoCornerBottomLeft2);
    lv_obj_set_width(ui_LogoCornerBottomLeft2, 20);
    lv_obj_set_height(ui_LogoCornerBottomLeft2, 10);
    lv_obj_set_align(ui_LogoCornerBottomLeft2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_LogoCornerBottomLeft2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoCornerBottomLeft2, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerBottomLeft2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerBottomLeft2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerFillBottomLeft2 = lv_obj_create(ui_LogoGroup2);
    lv_obj_remove_style_all(ui_LogoCornerFillBottomLeft2);
    lv_obj_set_width(ui_LogoCornerFillBottomLeft2, 15);
    lv_obj_set_height(ui_LogoCornerFillBottomLeft2, 15);
    lv_obj_set_x(ui_LogoCornerFillBottomLeft2, -5);
    lv_obj_set_y(ui_LogoCornerFillBottomLeft2, 0);
    lv_obj_set_align(ui_LogoCornerFillBottomLeft2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_LogoCornerFillBottomLeft2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoCornerFillBottomLeft2, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoCornerFillBottomLeft2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomLeft2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomLeft2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerBottomRight2 = lv_obj_create(ui_LogoGroup2);
    lv_obj_remove_style_all(ui_LogoCornerBottomRight2);
    lv_obj_set_width(ui_LogoCornerBottomRight2, 20);
    lv_obj_set_height(ui_LogoCornerBottomRight2, 10);
    lv_obj_set_align(ui_LogoCornerBottomRight2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_LogoCornerBottomRight2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoCornerBottomRight2, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerBottomRight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerBottomRight2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerFillBottomRight2 = lv_obj_create(ui_LogoGroup2);
    lv_obj_remove_style_all(ui_LogoCornerFillBottomRight2);
    lv_obj_set_width(ui_LogoCornerFillBottomRight2, 15);
    lv_obj_set_height(ui_LogoCornerFillBottomRight2, 15);
    lv_obj_set_x(ui_LogoCornerFillBottomRight2, 5);
    lv_obj_set_y(ui_LogoCornerFillBottomRight2, 0);
    lv_obj_set_align(ui_LogoCornerFillBottomRight2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_LogoCornerFillBottomRight2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoCornerFillBottomRight2, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoCornerFillBottomRight2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomRight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomRight2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoOutlay2 = lv_obj_create(ui_LogoGroup2);
    lv_obj_remove_style_all(ui_LogoOutlay2);
    lv_obj_set_width(ui_LogoOutlay2, 80);
    lv_obj_set_height(ui_LogoOutlay2, 25);
    lv_obj_set_align(ui_LogoOutlay2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LogoOutlay2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoOutlay2, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoOutlay2, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoOutlay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoOutlay2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImage1 = lv_img_create(ui_LogoGroup2);
    lv_img_set_src(ui_LogoImage1, &ui_img_mtalogo_png);
    lv_obj_set_width(ui_LogoImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LogoImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LogoImage1, 80);

    ui_SensorSelectionLabel = lv_label_create(ui_Widget2);
    lv_obj_set_width(ui_SensorSelectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorSelectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorSelectionLabel, 0);
    lv_obj_set_y(ui_SensorSelectionLabel, 10);
    lv_obj_set_align(ui_SensorSelectionLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SensorSelectionLabel, "Sensor Selection");
    lv_obj_clear_flag(ui_SensorSelectionLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SensorSelectionLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SensorSelectionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SensorSelectionLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackGroup2 = lv_obj_create(ui_Widget2);
    lv_obj_remove_style_all(ui_ButtonBackGroup2);
    lv_obj_set_width(ui_ButtonBackGroup2, 100);
    lv_obj_set_height(ui_ButtonBackGroup2, 40);
    lv_obj_clear_flag(ui_ButtonBackGroup2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonBackCornerBottomLeft2 = lv_obj_create(ui_ButtonBackGroup2);
    lv_obj_remove_style_all(ui_ButtonBackCornerBottomLeft2);
    lv_obj_set_width(ui_ButtonBackCornerBottomLeft2, 20);
    lv_obj_set_height(ui_ButtonBackCornerBottomLeft2, 20);
    lv_obj_set_align(ui_ButtonBackCornerBottomLeft2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_ButtonBackCornerBottomLeft2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackCornerBottomLeft2, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackCornerBottomLeft2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ButtonBackCornerBottomLeft2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackCornerTopRight2 = lv_obj_create(ui_ButtonBackGroup2);
    lv_obj_remove_style_all(ui_ButtonBackCornerTopRight2);
    lv_obj_set_width(ui_ButtonBackCornerTopRight2, 20);
    lv_obj_set_height(ui_ButtonBackCornerTopRight2, 20);
    lv_obj_set_align(ui_ButtonBackCornerTopRight2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ButtonBackCornerTopRight2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackCornerTopRight2, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackCornerTopRight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ButtonBackCornerTopRight2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack2 = lv_btn_create(ui_ButtonBackGroup2);
    lv_obj_set_width(ui_btnBack2, 100);
    lv_obj_set_height(ui_btnBack2, 40);
    lv_obj_add_flag(ui_btnBack2, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnBack2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_clip_corner(ui_btnBack2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackLabel2 = lv_label_create(ui_btnBack2);
    lv_obj_set_width(ui_ButtonBackLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonBackLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonBackLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonBackLabel2, "Back");
    lv_obj_set_style_text_font(ui_ButtonBackLabel2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorNameLabel = lv_label_create(ui_Widget2);
    lv_obj_set_width(ui_SensorNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorNameLabel, 20);
    lv_obj_set_y(ui_SensorNameLabel, 60);
    lv_label_set_text(ui_SensorNameLabel, "DHT11");
    lv_obj_clear_flag(ui_SensorNameLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SensorNameLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SensorNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SensorNameLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorInfoLabel = lv_label_create(ui_Widget2);
    lv_obj_set_width(ui_SensorInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorInfoLabel, 25);
    lv_obj_set_y(ui_SensorInfoLabel, 100);
    lv_label_set_text(ui_SensorInfoLabel, "DHT11 je senzor snimajici teplotu a vlhkost");
    lv_obj_clear_flag(ui_SensorInfoLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SensorInfoLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SensorInfoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPrev2 = lv_btn_create(ui_Widget2);
    lv_obj_set_width(ui_btnPrev2, 80);
    lv_obj_set_height(ui_btnPrev2, 40);
    lv_obj_set_x(ui_btnPrev2, 40);
    lv_obj_set_y(ui_btnPrev2, -20);
    lv_obj_set_align(ui_btnPrev2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btnPrev2, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnPrev2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ButtonPrevLabel2 = lv_label_create(ui_btnPrev2);
    lv_obj_set_width(ui_ButtonPrevLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonPrevLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonPrevLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonPrevLabel2, "Prev");

    ui_ContainerForImage = lv_obj_create(ui_Widget2);
    lv_obj_remove_style_all(ui_ContainerForImage);
    lv_obj_set_width(ui_ContainerForImage, 230);
    lv_obj_set_height(ui_ContainerForImage, 300);
    lv_obj_set_x(ui_ContainerForImage, -60);
    lv_obj_set_y(ui_ContainerForImage, -10);
    lv_obj_set_align(ui_ContainerForImage, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ContainerForImage,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerForImage, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerForImage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerForImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerForImage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerForImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerForImage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorImage = lv_img_create(ui_ContainerForImage);
    lv_obj_set_width(ui_SensorImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SensorImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SensorImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SensorImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SensorImage, 800);

    ui_btnNext2 = lv_btn_create(ui_Widget2);
    lv_obj_set_width(ui_btnNext2, 80);
    lv_obj_set_height(ui_btnNext2, 40);
    lv_obj_set_x(ui_btnNext2, -110);
    lv_obj_set_y(ui_btnNext2, -20);
    lv_obj_set_align(ui_btnNext2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnNext2, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnNext2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ButtonNextLabel2 = lv_label_create(ui_btnNext2);
    lv_obj_set_width(ui_ButtonNextLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonNextLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonNextLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonNextLabel2, "Next");

    ui_btnConfirm = lv_btn_create(ui_Widget2);
    lv_obj_set_width(ui_btnConfirm, 80);
    lv_obj_set_height(ui_btnConfirm, 40);
    lv_obj_set_x(ui_btnConfirm, -50);
    lv_obj_set_y(ui_btnConfirm, -20);
    lv_obj_set_align(ui_btnConfirm, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_btnConfirm, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnConfirm, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ButtonConfirmLabel = lv_label_create(ui_btnConfirm);
    lv_obj_set_width(ui_ButtonConfirmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonConfirmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonConfirmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonConfirmLabel, "Confirm");

}
