// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Widget = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Widget);
    lv_obj_set_width(ui_Widget, 760);
    lv_obj_set_height(ui_Widget, 440);
    lv_obj_set_align(ui_Widget, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Widget, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Widget, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Widget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Widget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Widget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Widget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Widget, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoGroup = lv_obj_create(ui_Widget);
    lv_obj_remove_style_all(ui_LogoGroup);
    lv_obj_set_width(ui_LogoGroup, 100);
    lv_obj_set_height(ui_LogoGroup, 25);
    lv_obj_set_align(ui_LogoGroup, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_LogoGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoCornerBottomLeft = lv_obj_create(ui_LogoGroup);
    lv_obj_remove_style_all(ui_LogoCornerBottomLeft);
    lv_obj_set_width(ui_LogoCornerBottomLeft, 20);
    lv_obj_set_height(ui_LogoCornerBottomLeft, 10);
    lv_obj_set_align(ui_LogoCornerBottomLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_LogoCornerBottomLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoCornerBottomLeft, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerBottomLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerFillBottomLeft = lv_obj_create(ui_LogoGroup);
    lv_obj_remove_style_all(ui_LogoCornerFillBottomLeft);
    lv_obj_set_width(ui_LogoCornerFillBottomLeft, 20);
    lv_obj_set_height(ui_LogoCornerFillBottomLeft, 20);
    lv_obj_set_x(ui_LogoCornerFillBottomLeft, -10);
    lv_obj_set_y(ui_LogoCornerFillBottomLeft, 0);
    lv_obj_set_align(ui_LogoCornerFillBottomLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_LogoCornerFillBottomLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoCornerFillBottomLeft, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoCornerFillBottomLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerBottomRight = lv_obj_create(ui_LogoGroup);
    lv_obj_remove_style_all(ui_LogoCornerBottomRight);
    lv_obj_set_width(ui_LogoCornerBottomRight, 20);
    lv_obj_set_height(ui_LogoCornerBottomRight, 10);
    lv_obj_set_align(ui_LogoCornerBottomRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_LogoCornerBottomRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoCornerBottomRight, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerBottomRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerFillBottomRight = lv_obj_create(ui_LogoGroup);
    lv_obj_remove_style_all(ui_LogoCornerFillBottomRight);
    lv_obj_set_width(ui_LogoCornerFillBottomRight, 20);
    lv_obj_set_height(ui_LogoCornerFillBottomRight, 20);
    lv_obj_set_x(ui_LogoCornerFillBottomRight, 10);
    lv_obj_set_y(ui_LogoCornerFillBottomRight, 0);
    lv_obj_set_align(ui_LogoCornerFillBottomRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_LogoCornerFillBottomRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoCornerFillBottomRight, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoCornerFillBottomRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoOutlay = lv_obj_create(ui_LogoGroup);
    lv_obj_remove_style_all(ui_LogoOutlay);
    lv_obj_set_width(ui_LogoOutlay, 80);
    lv_obj_set_height(ui_LogoOutlay, 25);
    lv_obj_set_align(ui_LogoOutlay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LogoOutlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoOutlay, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoOutlay, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoOutlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoOutlay, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImage = lv_img_create(ui_LogoGroup);
    lv_img_set_src(ui_LogoImage, &ui_img_mtalogo_png);
    lv_obj_set_width(ui_LogoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LogoImage, 80);

    ui_Chart = lv_chart_create(ui_Widget);
    lv_obj_set_width(ui_Chart, 410);
    lv_obj_set_height(ui_Chart, 280);
    lv_obj_set_x(ui_Chart, 150);
    lv_obj_set_y(ui_Chart, 12);
    lv_obj_set_align(ui_Chart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Chart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_Chart, 9, 10);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_X, 10, 0, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart_series_1 = lv_chart_add_series(ui_Chart, lv_color_hex(0xFFAF00),
                                                                LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_1, ui_Chart_series_1_array);
    lv_chart_series_t * ui_Chart_series_2 = lv_chart_add_series(ui_Chart, lv_color_hex(0x009BFF),
                                                                LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart_series_2_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_2, ui_Chart_series_2_array);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_MainLabel = lv_label_create(ui_Widget);
    lv_obj_set_width(ui_MainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabel, 0);
    lv_obj_set_y(ui_MainLabel, 10);
    lv_obj_set_align(ui_MainLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MainLabel, "DHT11");
    lv_obj_clear_flag(ui_MainLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MainLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPrev = lv_btn_create(ui_Widget);
    lv_obj_set_width(ui_btnPrev, 80);
    lv_obj_set_height(ui_btnPrev, 40);
    lv_obj_set_x(ui_btnPrev, 35);
    lv_obj_set_y(ui_btnPrev, -40);
    lv_obj_set_align(ui_btnPrev, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btnPrev, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnPrev, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ButtonPrevLabel = lv_label_create(ui_btnPrev);
    lv_obj_set_width(ui_ButtonPrevLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonPrevLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonPrevLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonPrevLabel, "Prev");

    ui_ButtonBackGroup = lv_obj_create(ui_Widget);
    lv_obj_remove_style_all(ui_ButtonBackGroup);
    lv_obj_set_width(ui_ButtonBackGroup, 100);
    lv_obj_set_height(ui_ButtonBackGroup, 40);
    lv_obj_clear_flag(ui_ButtonBackGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonBackCornerBottomLeft = lv_obj_create(ui_ButtonBackGroup);
    lv_obj_remove_style_all(ui_ButtonBackCornerBottomLeft);
    lv_obj_set_width(ui_ButtonBackCornerBottomLeft, 20);
    lv_obj_set_height(ui_ButtonBackCornerBottomLeft, 20);
    lv_obj_set_align(ui_ButtonBackCornerBottomLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_ButtonBackCornerBottomLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackCornerBottomLeft, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackCornerBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ButtonBackCornerBottomLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackCornerTopRight = lv_obj_create(ui_ButtonBackGroup);
    lv_obj_remove_style_all(ui_ButtonBackCornerTopRight);
    lv_obj_set_width(ui_ButtonBackCornerTopRight, 20);
    lv_obj_set_height(ui_ButtonBackCornerTopRight, 20);
    lv_obj_set_align(ui_ButtonBackCornerTopRight, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ButtonBackCornerTopRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackCornerTopRight, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackCornerTopRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ButtonBackCornerTopRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack = lv_btn_create(ui_ButtonBackGroup);
    lv_obj_set_width(ui_btnBack, 100);
    lv_obj_set_height(ui_btnBack, 40);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnBack, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_clip_corner(ui_btnBack, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackLabel = lv_label_create(ui_btnBack);
    lv_obj_set_width(ui_ButtonBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonBackLabel, "Back");
    lv_obj_set_style_text_font(ui_ButtonBackLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnNext = lv_btn_create(ui_Widget);
    lv_obj_set_width(ui_btnNext, 80);
    lv_obj_set_height(ui_btnNext, 40);
    lv_obj_set_x(ui_btnNext, 183);
    lv_obj_set_y(ui_btnNext, -40);
    lv_obj_set_align(ui_btnNext, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btnNext, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnNext, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ButtonNextLabel = lv_label_create(ui_btnNext);
    lv_obj_set_width(ui_ButtonNextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonNextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonNextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonNextLabel, "Next");

    ui_ContainerForHumidity = lv_obj_create(ui_Widget);
    lv_obj_remove_style_all(ui_ContainerForHumidity);
    lv_obj_set_width(ui_ContainerForHumidity, 230);
    lv_obj_set_height(ui_ContainerForHumidity, 118);
    lv_obj_set_x(ui_ContainerForHumidity, -230);
    lv_obj_set_y(ui_ContainerForHumidity, 55);
    lv_obj_set_align(ui_ContainerForHumidity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerForHumidity,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerForHumidity, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerForHumidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerForHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerForHumidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerForHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerForHumidity, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VisualColorForHumidity = lv_obj_create(ui_ContainerForHumidity);
    lv_obj_remove_style_all(ui_VisualColorForHumidity);
    lv_obj_set_width(ui_VisualColorForHumidity, 20);
    lv_obj_set_height(ui_VisualColorForHumidity, 20);
    lv_obj_set_x(ui_VisualColorForHumidity, -10);
    lv_obj_set_y(ui_VisualColorForHumidity, 10);
    lv_obj_set_align(ui_VisualColorForHumidity, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_VisualColorForHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VisualColorForHumidity, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VisualColorForHumidity, lv_color_hex(0xFFAF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VisualColorForHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDescHumidity = lv_label_create(ui_ContainerForHumidity);
    lv_obj_set_width(ui_LabelDescHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDescHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDescHumidity, 0);
    lv_obj_set_y(ui_LabelDescHumidity, 32);
    lv_obj_set_align(ui_LabelDescHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDescHumidity, "[%]");
    lv_obj_clear_flag(ui_LabelDescHumidity,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelDescHumidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDescHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDescHumidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValueHumidity = lv_label_create(ui_ContainerForHumidity);
    lv_obj_set_width(ui_LabelValueHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValueHumidity, 0);
    lv_obj_set_y(ui_LabelValueHumidity, 15);
    lv_obj_set_align(ui_LabelValueHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueHumidity, "0");
    lv_obj_clear_flag(ui_LabelValueHumidity,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelValueHumidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelValueHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueHumidity, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTypeHumidity = lv_label_create(ui_ContainerForHumidity);
    lv_obj_set_width(ui_LabelTypeHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTypeHumidity, 15);
    lv_obj_set_y(ui_LabelTypeHumidity, 10);
    lv_label_set_text(ui_LabelTypeHumidity, "Vlhkost");
    lv_obj_set_style_text_color(ui_LabelTypeHumidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerForTemperature = lv_obj_create(ui_Widget);
    lv_obj_remove_style_all(ui_ContainerForTemperature);
    lv_obj_set_width(ui_ContainerForTemperature, 230);
    lv_obj_set_height(ui_ContainerForTemperature, 118);
    lv_obj_set_x(ui_ContainerForTemperature, -230);
    lv_obj_set_y(ui_ContainerForTemperature, -85);
    lv_obj_set_align(ui_ContainerForTemperature, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerForTemperature,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerForTemperature, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerForTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerForTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerForTemperature, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VisualColorForTemperature = lv_obj_create(ui_ContainerForTemperature);
    lv_obj_remove_style_all(ui_VisualColorForTemperature);
    lv_obj_set_width(ui_VisualColorForTemperature, 20);
    lv_obj_set_height(ui_VisualColorForTemperature, 20);
    lv_obj_set_x(ui_VisualColorForTemperature, -10);
    lv_obj_set_y(ui_VisualColorForTemperature, 10);
    lv_obj_set_align(ui_VisualColorForTemperature, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_VisualColorForTemperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VisualColorForTemperature, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VisualColorForTemperature, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VisualColorForTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValueTemperature = lv_label_create(ui_ContainerForTemperature);
    lv_obj_set_width(ui_LabelValueTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValueTemperature, 0);
    lv_obj_set_y(ui_LabelValueTemperature, -5);
    lv_obj_set_align(ui_LabelValueTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueTemperature, "0");
    lv_obj_clear_flag(ui_LabelValueTemperature,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelValueTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelValueTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueTemperature, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDescTemperature = lv_label_create(ui_ContainerForTemperature);
    lv_obj_set_width(ui_LabelDescTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDescTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDescTemperature, 0);
    lv_obj_set_y(ui_LabelDescTemperature, 30);
    lv_obj_set_align(ui_LabelDescTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDescTemperature, "[°C]");
    lv_obj_clear_flag(ui_LabelDescTemperature,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelDescTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDescTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDescTemperature, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTypeTemperature = lv_label_create(ui_ContainerForTemperature);
    lv_obj_set_width(ui_LabelTypeTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTypeTemperature, 15);
    lv_obj_set_y(ui_LabelTypeTemperature, 10);
    lv_label_set_text(ui_LabelTypeTemperature, "Teplota");
    lv_obj_set_style_text_color(ui_LabelTypeTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerForSingleValue = lv_obj_create(ui_Widget);
    lv_obj_remove_style_all(ui_ContainerForSingleValue);
    lv_obj_set_width(ui_ContainerForSingleValue, 230);
    lv_obj_set_height(ui_ContainerForSingleValue, 118);
    lv_obj_set_x(ui_ContainerForSingleValue, -230);
    lv_obj_set_y(ui_ContainerForSingleValue, 55);
    lv_obj_set_align(ui_ContainerForSingleValue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerForSingleValue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerForSingleValue,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerForSingleValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerForSingleValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerForSingleValue, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerForSingleValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerForSingleValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerForSingleValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VisualColorForSingleValue = lv_obj_create(ui_ContainerForSingleValue);
    lv_obj_remove_style_all(ui_VisualColorForSingleValue);
    lv_obj_set_width(ui_VisualColorForSingleValue, 20);
    lv_obj_set_height(ui_VisualColorForSingleValue, 20);
    lv_obj_set_x(ui_VisualColorForSingleValue, -10);
    lv_obj_set_y(ui_VisualColorForSingleValue, 10);
    lv_obj_set_align(ui_VisualColorForSingleValue, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_VisualColorForSingleValue, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VisualColorForSingleValue, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VisualColorForSingleValue, lv_color_hex(0xFFAF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VisualColorForSingleValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSingleValue = lv_label_create(ui_ContainerForSingleValue);
    lv_obj_set_width(ui_LabelSingleValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSingleValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSingleValue, 0);
    lv_obj_set_y(ui_LabelSingleValue, -5);
    lv_obj_set_align(ui_LabelSingleValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSingleValue, "0");
    lv_obj_clear_flag(ui_LabelSingleValue,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSingleValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSingleValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSingleValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSingleValueDesc = lv_label_create(ui_ContainerForSingleValue);
    lv_obj_set_width(ui_LabelSingleValueDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSingleValueDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSingleValueDesc, 0);
    lv_obj_set_y(ui_LabelSingleValueDesc, 30);
    lv_obj_set_align(ui_LabelSingleValueDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSingleValueDesc, "[Lux]");
    lv_obj_clear_flag(ui_LabelSingleValueDesc,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSingleValueDesc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSingleValueDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSingleValueDesc, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Widget = ui_Widget;
    uic_Chart = ui_Chart;
    uic_Label = ui_MainLabel;
    uic_btnPrev = ui_btnPrev;
    uic_ButtonPrevLabel = ui_ButtonPrevLabel;
    uic_btnNext = ui_btnNext;
    uic_ButtonNextLabel = ui_ButtonNextLabel;
    uic_ContainerForHumidity = ui_ContainerForHumidity;
    uic_VisualColorFor = ui_VisualColorForHumidity;
    uic_LabelDescHumidity = ui_LabelDescHumidity;
    uic_LabelValueHumidity = ui_LabelValueHumidity;
    uic_LabelTypeHumidity = ui_LabelTypeHumidity;
    uic_ContainerForTemperature = ui_ContainerForTemperature;
    uic_VisualColorForTemperature = ui_VisualColorForTemperature;
    uic_LabelValueTemperature = ui_LabelValueTemperature;
    uic_LabelDescTemperature = ui_LabelDescTemperature;
    uic_LabelTypeTemperature = ui_LabelTypeTemperature;
    uic_ContainerForSingleValue = ui_ContainerForSingleValue;
    uic_VisualColorForSingleValue = ui_VisualColorForSingleValue;
    uic_LabelSingleValue = ui_LabelSingleValue;
    uic_LabelSingleValueDesc = ui_LabelSingleValueDesc;

}
