// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Widget1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Widget1);
    lv_obj_set_width(ui_Widget1, 760);
    lv_obj_set_height(ui_Widget1, 440);
    lv_obj_set_align(ui_Widget1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Widget1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Widget1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Widget1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Widget1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Widget1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Widget1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Widget1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStartGroup = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ButtonStartGroup);
    lv_obj_set_width(ui_ButtonStartGroup, 100);
    lv_obj_set_height(ui_ButtonStartGroup, 45);
    lv_obj_set_align(ui_ButtonStartGroup, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ButtonStartGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonStartCornerTopLeft = lv_obj_create(ui_ButtonStartGroup);
    lv_obj_remove_style_all(ui_ButtonStartCornerTopLeft);
    lv_obj_set_width(ui_ButtonStartCornerTopLeft, 20);
    lv_obj_set_height(ui_ButtonStartCornerTopLeft, 20);
    lv_obj_clear_flag(ui_ButtonStartCornerTopLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonStartCornerTopLeft, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonStartCornerTopLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ButtonStartCornerTopLeft, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStartCornerBottomRight = lv_obj_create(ui_ButtonStartGroup);
    lv_obj_remove_style_all(ui_ButtonStartCornerBottomRight);
    lv_obj_set_width(ui_ButtonStartCornerBottomRight, 20);
    lv_obj_set_height(ui_ButtonStartCornerBottomRight, 20);
    lv_obj_set_align(ui_ButtonStartCornerBottomRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ButtonStartCornerBottomRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonStartCornerBottomRight, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonStartCornerBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ButtonStartCornerBottomRight, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnStart = lv_btn_create(ui_ButtonStartGroup);
    lv_obj_set_width(ui_btnStart, 100);
    lv_obj_set_height(ui_btnStart, 45);
    lv_obj_add_flag(ui_btnStart, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_btnStart, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_clip_corner(ui_btnStart, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStartLabel = lv_label_create(ui_btnStart);
    lv_obj_set_width(ui_ButtonStartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonStartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonStartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonStartLabel, "Start");
    lv_obj_set_style_text_font(ui_ButtonStartLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoGroup1 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_LogoGroup1);
    lv_obj_set_width(ui_LogoGroup1, 100);
    lv_obj_set_height(ui_LogoGroup1, 25);
    lv_obj_set_align(ui_LogoGroup1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_LogoGroup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoCornerBottomLeft1 = lv_obj_create(ui_LogoGroup1);
    lv_obj_remove_style_all(ui_LogoCornerBottomLeft1);
    lv_obj_set_width(ui_LogoCornerBottomLeft1, 20);
    lv_obj_set_height(ui_LogoCornerBottomLeft1, 10);
    lv_obj_set_align(ui_LogoCornerBottomLeft1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_LogoCornerBottomLeft1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoCornerBottomLeft1, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerBottomLeft1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerBottomLeft1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerFillBottomLeft1 = lv_obj_create(ui_LogoGroup1);
    lv_obj_remove_style_all(ui_LogoCornerFillBottomLeft1);
    lv_obj_set_width(ui_LogoCornerFillBottomLeft1, 15);
    lv_obj_set_height(ui_LogoCornerFillBottomLeft1, 15);
    lv_obj_set_x(ui_LogoCornerFillBottomLeft1, -5);
    lv_obj_set_y(ui_LogoCornerFillBottomLeft1, 0);
    lv_obj_set_align(ui_LogoCornerFillBottomLeft1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_LogoCornerFillBottomLeft1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoCornerFillBottomLeft1, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoCornerFillBottomLeft1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomLeft1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomLeft1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerBottomRight1 = lv_obj_create(ui_LogoGroup1);
    lv_obj_remove_style_all(ui_LogoCornerBottomRight1);
    lv_obj_set_width(ui_LogoCornerBottomRight1, 20);
    lv_obj_set_height(ui_LogoCornerBottomRight1, 10);
    lv_obj_set_align(ui_LogoCornerBottomRight1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_LogoCornerBottomRight1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoCornerBottomRight1, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerBottomRight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerBottomRight1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoCornerFillBottomRight1 = lv_obj_create(ui_LogoGroup1);
    lv_obj_remove_style_all(ui_LogoCornerFillBottomRight1);
    lv_obj_set_width(ui_LogoCornerFillBottomRight1, 15);
    lv_obj_set_height(ui_LogoCornerFillBottomRight1, 15);
    lv_obj_set_x(ui_LogoCornerFillBottomRight1, 5);
    lv_obj_set_y(ui_LogoCornerFillBottomRight1, 0);
    lv_obj_set_align(ui_LogoCornerFillBottomRight1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_LogoCornerFillBottomRight1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoCornerFillBottomRight1, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoCornerFillBottomRight1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoCornerFillBottomRight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoCornerFillBottomRight1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoOutlay1 = lv_obj_create(ui_LogoGroup1);
    lv_obj_remove_style_all(ui_LogoOutlay1);
    lv_obj_set_width(ui_LogoOutlay1, 80);
    lv_obj_set_height(ui_LogoOutlay1, 25);
    lv_obj_set_align(ui_LogoOutlay1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LogoOutlay1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LogoOutlay1, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LogoOutlay1, lv_color_hex(0x055DA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoOutlay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_LogoOutlay1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImage2 = lv_img_create(ui_LogoGroup1);
    lv_img_set_src(ui_LogoImage2, &ui_img_mtalogo_png);
    lv_obj_set_width(ui_LogoImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LogoImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LogoImage2, 80);

    ui_MainMenuLabel = lv_label_create(ui_Widget1);
    lv_obj_set_width(ui_MainMenuLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenuLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenuLabel, 0);
    lv_obj_set_y(ui_MainMenuLabel, 10);
    lv_obj_set_align(ui_MainMenuLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MainMenuLabel, "Main Menu");
    lv_obj_clear_flag(ui_MainMenuLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MainMenuLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainMenuLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPin0 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ContainerPin0);
    lv_obj_set_width(ui_ContainerPin0, 220);
    lv_obj_set_height(ui_ContainerPin0, 130);
    lv_obj_set_x(ui_ContainerPin0, 20);
    lv_obj_set_y(ui_ContainerPin0, -80);
    lv_obj_set_align(ui_ContainerPin0, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerPin0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerPin0, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerPin0, lv_color_hex(0x4CB9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPin0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContainerPin0, lv_color_hex(0x333232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContainerPin0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ContainerPin0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ContainerPin0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ContainerPin0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ContainerPin0, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor0 = lv_label_create(ui_ContainerPin0);
    lv_obj_set_width(ui_LabelSensor0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensor0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor0, "DHT11");
    lv_obj_clear_flag(ui_LabelSensor0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSensor0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor0, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPinNumber0 = lv_label_create(ui_ContainerPin0);
    lv_obj_set_width(ui_LabelPinNumber0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinNumber0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinNumber0, 15);
    lv_obj_set_y(ui_LabelPinNumber0, 10);
    lv_label_set_text(ui_LabelPinNumber0, "Pin 0");
    lv_obj_set_style_text_color(ui_LabelPinNumber0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPinNumber0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPin1 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ContainerPin1);
    lv_obj_set_width(ui_ContainerPin1, 220);
    lv_obj_set_height(ui_ContainerPin1, 130);
    lv_obj_set_x(ui_ContainerPin1, 20);
    lv_obj_set_y(ui_ContainerPin1, 80);
    lv_obj_set_align(ui_ContainerPin1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContainerPin1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerPin1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerPin1, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPin1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContainerPin1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContainerPin1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ContainerPin1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ContainerPin1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ContainerPin1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ContainerPin1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor1 = lv_label_create(ui_ContainerPin1);
    lv_obj_set_width(ui_LabelSensor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor1, "Pin 1");
    lv_obj_clear_flag(ui_LabelSensor1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSensor1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPinNumber1 = lv_label_create(ui_ContainerPin1);
    lv_obj_set_width(ui_LabelPinNumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinNumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinNumber1, 15);
    lv_obj_set_y(ui_LabelPinNumber1, 10);
    lv_label_set_text(ui_LabelPinNumber1, "Unused");
    lv_obj_set_style_text_color(ui_LabelPinNumber1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPinNumber1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPin2 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ContainerPin2);
    lv_obj_set_width(ui_ContainerPin2, 220);
    lv_obj_set_height(ui_ContainerPin2, 130);
    lv_obj_set_x(ui_ContainerPin2, -5);
    lv_obj_set_y(ui_ContainerPin2, -80);
    lv_obj_set_align(ui_ContainerPin2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPin2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerPin2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerPin2, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContainerPin2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContainerPin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ContainerPin2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ContainerPin2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ContainerPin2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ContainerPin2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor2 = lv_label_create(ui_ContainerPin2);
    lv_obj_set_width(ui_LabelSensor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor2, "Pin 1");
    lv_obj_clear_flag(ui_LabelSensor2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSensor2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPinNumber2 = lv_label_create(ui_ContainerPin2);
    lv_obj_set_width(ui_LabelPinNumber2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinNumber2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinNumber2, 15);
    lv_obj_set_y(ui_LabelPinNumber2, 10);
    lv_label_set_text(ui_LabelPinNumber2, "Unused");
    lv_obj_set_style_text_color(ui_LabelPinNumber2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPinNumber2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPin3 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ContainerPin3);
    lv_obj_set_width(ui_ContainerPin3, 220);
    lv_obj_set_height(ui_ContainerPin3, 130);
    lv_obj_set_x(ui_ContainerPin3, -5);
    lv_obj_set_y(ui_ContainerPin3, 80);
    lv_obj_set_align(ui_ContainerPin3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPin3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerPin3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerPin3, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPin3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContainerPin3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContainerPin3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ContainerPin3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ContainerPin3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ContainerPin3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ContainerPin3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor3 = lv_label_create(ui_ContainerPin3);
    lv_obj_set_width(ui_LabelSensor3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensor3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor3, "Pin 1");
    lv_obj_clear_flag(ui_LabelSensor3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSensor3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPinNumber3 = lv_label_create(ui_ContainerPin3);
    lv_obj_set_width(ui_LabelPinNumber3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinNumber3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinNumber3, 15);
    lv_obj_set_y(ui_LabelPinNumber3, 10);
    lv_label_set_text(ui_LabelPinNumber3, "Unused");
    lv_obj_set_style_text_color(ui_LabelPinNumber3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPinNumber3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPin4 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ContainerPin4);
    lv_obj_set_width(ui_ContainerPin4, 220);
    lv_obj_set_height(ui_ContainerPin4, 130);
    lv_obj_set_x(ui_ContainerPin4, -30);
    lv_obj_set_y(ui_ContainerPin4, -80);
    lv_obj_set_align(ui_ContainerPin4, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ContainerPin4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerPin4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerPin4, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPin4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContainerPin4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContainerPin4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ContainerPin4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ContainerPin4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ContainerPin4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ContainerPin4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor4 = lv_label_create(ui_ContainerPin4);
    lv_obj_set_width(ui_LabelSensor4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensor4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor4, "Pin 1");
    lv_obj_clear_flag(ui_LabelSensor4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSensor4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPinNumber4 = lv_label_create(ui_ContainerPin4);
    lv_obj_set_width(ui_LabelPinNumber4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinNumber4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinNumber4, 15);
    lv_obj_set_y(ui_LabelPinNumber4, 10);
    lv_label_set_text(ui_LabelPinNumber4, "Unused");
    lv_obj_set_style_text_color(ui_LabelPinNumber4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPinNumber4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPin5 = lv_obj_create(ui_Widget1);
    lv_obj_remove_style_all(ui_ContainerPin5);
    lv_obj_set_width(ui_ContainerPin5, 220);
    lv_obj_set_height(ui_ContainerPin5, 130);
    lv_obj_set_x(ui_ContainerPin5, -30);
    lv_obj_set_y(ui_ContainerPin5, 80);
    lv_obj_set_align(ui_ContainerPin5, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ContainerPin5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ContainerPin5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerPin5, lv_color_hex(0x009BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerPin5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContainerPin5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContainerPin5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ContainerPin5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ContainerPin5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ContainerPin5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ContainerPin5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor5 = lv_label_create(ui_ContainerPin5);
    lv_obj_set_width(ui_LabelSensor5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSensor5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor5, "Pin 1");
    lv_obj_clear_flag(ui_LabelSensor5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSensor5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor5, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPinNumber5 = lv_label_create(ui_ContainerPin5);
    lv_obj_set_width(ui_LabelPinNumber5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinNumber5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinNumber5, 15);
    lv_obj_set_y(ui_LabelPinNumber5, 10);
    lv_label_set_text(ui_LabelPinNumber5, "Unused");
    lv_obj_set_style_text_color(ui_LabelPinNumber5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPinNumber5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
