// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Booting_screen_init(void)
{
    ui_Booting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Booting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Booting, lv_color_hex(0x1380EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Booting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBooting = lv_label_create(ui_Booting);
    lv_obj_set_width(ui_LabelBooting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBooting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBooting, -7);
    lv_obj_set_y(ui_LabelBooting, -56);
    lv_obj_set_align(ui_LabelBooting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBooting, "BOOTING");
    lv_obj_set_style_text_color(ui_LabelBooting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBooting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBooting, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPleaseWait = lv_label_create(ui_Booting);
    lv_obj_set_width(ui_LabelPleaseWait, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPleaseWait, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPleaseWait, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPleaseWait, "Please wait\n");
    lv_obj_set_style_text_color(ui_LabelPleaseWait, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPleaseWait, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPleaseWait, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerBooting = lv_spinner_create(ui_Booting, 1000, 90);
    lv_obj_set_width(ui_SpinnerBooting, 80);
    lv_obj_set_height(ui_SpinnerBooting, 80);
    lv_obj_set_x(ui_SpinnerBooting, -1);
    lv_obj_set_y(ui_SpinnerBooting, 73);
    lv_obj_set_align(ui_SpinnerBooting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerBooting, LV_OBJ_FLAG_CLICKABLE);      /// Flags
}
